### ISSUE TITLE
profit% in workplace.ipynb

### ISSUE THREAD

**Issue by jo24** [mason-lee19/stockTrader_NEAT#1]
@ line 651000

buy_price 46811.128906
sell_price 46063.269531
profit% 23.783924 ?? 

wouldn't it rather be -1.597610% ?

But thank you for sharing the concep ;)

**Comment by mason-lee19** [comment]
> @ line 651000
> 
> buy_price 46811.128906 sell_price 46063.269531 profit% 23.783924 ??
> 
> wouldn't it rather be -1.597610% ?
> 
> But thank you for sharing the concep ;)

Hey Jo24,

Thank you for taking a look at my work!
The profit% in the workplace notebook is cumulative through runs not exact profit off that trade. 
I decided to utilize Cumulative Profit as a main indicator to capture the overall success of the NEAT network across the multiple trade windows per run.

Regards,
Mason
